AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  oaiName:
    Type: String

Resources:
  cloudfrontoriginaccessidentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref oaiName

Outputs:
  oaiId:
    Value: !GetAtt cloudfrontoriginaccessidentity.Id
    Export:
      Name: !Sub "${AWS::StackName}-Id"
  S3CanonicalUserId:
    Value: !GetAtt cloudfrontoriginaccessidentity.S3CanonicalUserId
    Export: 
      Name: !Sub "${AWS::StackName}-S3CanonicalUserId"


