AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  customDomain:
    Type: String
  acmCertificateArn:
    Type: String
  s3BucketStackName:
    Type: String
  oaiStackName:
    Type: String
  defaultRootObject:
    Type: String
  viewerProtocol:
    Type: String
    Default: redirect-to-https
    AllowedValues:
    - allow-all
    - https-only
    - redirect-to-https

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !ImportValue 
            Fn::Sub: "${s3BucketStackName}-S3BucketName"
        Origins: 
          - DomainName:  !ImportValue 
              Fn::Sub: "${s3BucketStackName}-S3BucketDomainName"
            Id: !ImportValue 
                Fn::Sub: "${s3BucketStackName}-S3BucketName"
            S3OriginConfig:
              OriginAccessIdentity: !Sub 
                  - 'origin-access-identity/cloudfront/${CloudfrontS3OAI}'
                  - CloudfrontS3OAI: !ImportValue 
                      Fn::Sub: "${oaiStackName}-Id"
        Enabled: true
        Aliases: 
          - !Ref customDomain
        ViewerCertificate:
          AcmCertificateArn: !Ref acmCertificateArn
          MinimumProtocolVersion: 'TLSv1.2_2021'
          SslSupportMethod: 'sni-only'
        DefaultRootObject: !Ref defaultRootObject
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: !Sub '/${defaultRootObject}'
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: !Sub '/${defaultRootObject}'
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: !ImportValue 
              Fn::Sub: "${s3BucketStackName}-S3BucketName"
          ViewerProtocolPolicy: !Ref viewerProtocol
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

Outputs:
  CloudFrontDistributionId:
    Value: !GetAtt CloudFrontDistribution.Id
    Export:
      Name: !Sub "${AWS::StackName}-Id"
  CloudFrontDistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-DomainName"