name: Terraform IaaC

on:
  push:
    branches:
      - none

jobs:
 IaC:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Configure Elastic Container Registry credentials
        run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCES_KEY }} --region us-east-1       
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCES_KEY }} --region us-east-1
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            aws_access_key_id: ${{ secrets.AWS_ACCES_KEY }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCES_KEY }}

      - name: Terrform initialization
        run: terraform init
        working-directory: src/

      - name: Build infrastructure
        run: |
          terraform validate 
 